config/routes.rb
DojoDove::Application.routes.draw do
  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resource :profile, :only => [:show, :edit, :update]

  root :to => 'dashboard#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :bio, :organization, :website
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :twitter]


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :username
  # attr_accessible :title, :body

  has_one :profile

  after_create :make_profile

  def name
    if self.profile.first_name && self.profile.last_name
      self.profile.first_name + ' ' + self.profile.last_name
    else
      self.email
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end    
  end

  def password_required? 
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:email => data["email"]).first

      unless user
          user = User.create(name: data["name"],
               email: data["email"],
               password: Devise.friendly_token[0,20]
              )
      end
      user
  end

  private

  def make_profile
    self.create_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.create
  end
 
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update_attributes(params[:profile])
      redirect_to profile_path, :notice => "You have successsfully updated your profile."
    else
      render :edit
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/profile/edit'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # def all
  #   @user = User.from_omniauth(request.env["omniauth.auth"])
  #   if @user.persisted?
  #     sign_in_and_redirect user, notice: "Signed in!"
  #   else
  #     session["devise.user_attributes"] = user.attributes
  #     redirect_to new_user_registration_url
  #   end
  #   alias_method :facebook, :all
  #  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h3>Please correct these problems:</h3>
    <h4><ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul></h4>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-error">Please correct these problems: 
    <ul>
      <li><%= flash[:error] %></li>
    </ul>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-error">
    <strong>Please correct these problems:</strong>
    <ul>
      <li><%= flash[:alert] %></li>
    </ul>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
      
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <div class="nav-collapse">

          <ul class="nav pull-left">
            <li><%= link_to "Home", root_path %></li>
          </ul>

          <ul class="nav pull-left">
            <li><%= link_to 'Help Requests' %></li>
          </ul>

          <ul class="nav pull-left">
            <li class='dropdown'>
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Tools" %></li>
                <li><%= link_to "Subjects" %></li>
                <li><%= link_to "Types" %></li>
              </ul>
            </li>
          </ul>

          <ul class="nav pull-left">
            <% if user_signed_in? %>
              <li class='dropdown'>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'View profile' %></li>
                  <li><%= link_to 'Edit profile', edit_profile_path %></li>
                  <li><%= link_to 'Edit account' %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li class='dropdown'>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign In<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <div class='container-fluid pad_top'>
                    <%= form_for("user", :url => user_session_path) do |f| %>
                      <%= f.label 'Email:' %>
                      <%= f.text_field :email %>
                      <%= f.label 'Password:' %>
                      <%= f.password_field :password %>
                      <%= f.check_box :remember_me  %>
                      <%= f.label :remember_me, :class => 'make_inline' %>
                      <%= f.submit 'Sign in', :class => 'btn btn-primary make_block' %>
                      <%= link_to "Forgot your password?", new_password_path('user') %>
                    <% end %>
                  </div>
                  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
                  <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
                  <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>

                </ul>
              </li>
            <% end %>
          </ul>
              
               

          <ul class="nav pull-right">
            <li>
              <form class="navbar-search">
                <input type="text" class="search-query" placeholder="Search">
              </form>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
   
    <%= render :partial => 'layouts/flash', :locals => {:flash => flash} %>

    <h2><%= yield :title %></h2>

    <%= yield %>

  </div>

</body>
</html>

app/views/profiles/edit.html.erb
<% provide :title, 'Edit Profile' %>

<%= form_for @profile do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <%= f.label :organization %>
  <%= f.text_area :organization %>
  <%= f.label :website %>
  <%= f.text_area :website %>
  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

<p><%= link_to 'Cancel', profile_path, :class => 'btn' %></p>

app/views/profiles/show.html.erb
<% provide :title, "#{@profile.user.name}'s Profile" %>

<ul class="unstyled">
  <li><strong>First name:</strong> <%= @profile.first_name %></li>
  <li><strong>Last name:</strong> <%= @profile.last_name %></li>
  <li><strong>Email:</strong> <%= @profile.email %></li>
  <li><strong>Bio:</strong> <%= @profile.bio %></li>
  <li><strong>Organization:</strong> <%= @profile.organization %></li>
  <li><strong>Website:</strong> <%= @profile.website %></li>

</ul>

<p><%= link_to 'Edit profile', edit_profile_path, :class => 'btn' %></p>